import{a as x,i as c,S as M}from"./assets/vendor-BDaiwwc1.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const r of document.querySelectorAll('link[rel="modulepreload"]'))i(r);new MutationObserver(r=>{for(const o of r)if(o.type==="childList")for(const u of o.addedNodes)u.tagName==="LINK"&&u.rel==="modulepreload"&&i(u)}).observe(document,{childList:!0,subtree:!0});function l(r){const o={};return r.integrity&&(o.integrity=r.integrity),r.referrerPolicy&&(o.referrerPolicy=r.referrerPolicy),r.crossOrigin==="use-credentials"?o.credentials="include":r.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function i(r){if(r.ep)return;r.ep=!0;const o=l(r);fetch(r.href,o)}})();const R="48279024-d4145a4c2f3735ee57c61073f",$="https://pixabay.com/api/";async function b(e,t,l=15){try{return(await x.get($,{params:{key:R,q:e,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,per_page:l}})).data}catch(i){throw console.error("Помилка при отриманні зображень:",i),i}}function v(e){return e.map(({tags:t,webformatURL:l,likes:i,comments:r,views:o,downloads:u,largeImageURL:P})=>`
      <li class="card">
        <a href="${P}" class="gallery-item">
          <img class="card-img" src="${l}" alt="${t}" />
        </a>
        <div class="card-body">
          <ul class="card-value-list">
            <li class="card-value"><h3>Likes</h3><p>${i}</p></li>
            <li class="card-value"><h3>Views</h3><p>${o}</p></li>
            <li class="card-value"><h3>Comments</h3><p>${r}</p></li>
            <li class="card-value"><h3>Downloads</h3><p>${u}</p></li>
          </ul>
        </div>
      </li>`).join("")}function m(e,t,l=!1){if(!t.trim()){c.warning({title:"Увага!",message:"Нічого не знайдено. Спробуйте інший запит.",position:"topRight",timeout:3e3});return}l?e.insertAdjacentHTML("beforeend",t):e.innerHTML=t}function n(e,t){e.style.display=t?"block":"none"}function E(){var t;const e=((t=document.querySelector(".card"))==null?void 0:t.getBoundingClientRect().height)||0;window.scrollBy({top:e*2,behavior:"smooth"})}function y(){c.info({title:"Вибірка завершена",message:"We're sorry, but you've reached the end of search results.",position:"topRight",timeout:4e3})}function w(){new M(".gallery-item",{captionsData:"alt",captionDelay:250}).refresh()}const S=()=>{const e=document.querySelector(".loader");e&&(e.style.display="block")},q=()=>{const e=document.querySelector(".loader");e&&(e.style.display="none")},O=document.querySelector(".searchForm"),L=document.querySelector(".card-list"),s=document.querySelector(".load-more");let f="",a=1;const p=15;let g=0,h=1,d=!1;O.addEventListener("submit",async e=>{if(e.preventDefault(),f=e.target.querySelector("input").value.trim(),!f){c.error({title:"Помилка введення даних!",message:"Введіть значення у форму для пошуку зображень.",backgroundColor:"red",position:"topRight",timeout:3e3});return}a=1,g=0,d=!1,s.style.display="none",S();try{const t=await b(f,a,p);if(g=t.totalHits,h=Math.ceil(g/p),t.hits.length===0&&a===1)return c.warning({title:"Нічого не знайдено!",message:"Спробуйте змінити параметри пошуку.",position:"topRight",timeout:3e3}),m(L,"");if(m(L,v(t.hits)),w(),a>=h){d=!0,n(s,!1),y();return}n(s,!0)}catch{c.error({title:"Помилка сервера!",message:"Змініть параметри пошуку.",position:"topRight",timeout:3e3})}finally{q()}});s.addEventListener("click",async()=>{if(d){n(s,!1);return}a++,S(),n(s,!1);try{const e=await b(f,a,p);if(e.hits.length===0||a>=h){d=!0,n(s,!1),y();return}m(L,v(e.hits),!0),w(),E(),e.hits.length<p||a>=h?(d=!0,n(s,!1),y()):n(s,!0)}catch{c.error({title:"Перелік вичерпано",message:"Не вдалося отримати додаткові результати.",position:"topRight",timeout:3e3})}finally{q()}});
//# sourceMappingURL=index.js.map
